[project]
name = "foundry-systems"
version = "0.1.0"
description = "Systems"
authors = [
    {name = "Daniel Pfrommer", email = "dan.pfrommer@gmail.com"},
]
dependencies = [
    "foundry-core @ file:///${PROJECT_ROOT}/../core",
    "mujoco-mjx>=3.1.6",
    "shapely>=2.0.4",
    "robosuite>=1.4",
    "h5py>=3.11.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm]
distribution = true

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
