[package]
name = "noctis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "noctis"
crate-type = ["cdylib"]

[build-dependencies]
lalrpop = "0.19"

[dependencies]
pyo3 = "0.19.0"
lalrpop-util = "0.19"
logos = "0.12.1"
log = "0.4.13"
ordered-float = "4.2.1"
uuid = "1.9.1"
