[tool.poetry]
name = "stanza"
version = "0.0.1"
description = ""
authors = ["Daniel Pfrommer <dan.pfrommer@gmail.com>"]
readme = "README.md"
packages = [{include = "stanza"}]

[tool.poetry.dependencies]
python = "^3.10"

numpy="^1.26.3"
pandas="^2.1.4"
flax="^0.7.5"
einops="^0.7.0"
optax="^0.1.7"
chex="^0.1.85"
jax="^0.4.24"
jaxlib="^0.4.23"
wandb="^0.16.1"
tensorstore="^0.1.51"
ffmpegio="^0.9.0"
rich="^13.7.0"
matplotlib="^3.8.2"
plotly="^5.18.0"
ipykernel="^6.28.0"
nbformat="^5.9.2"
pytest="^7.4.4"

[tool.poetry.scripts]
launch = "stanza:launch"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"