[tool.poetry]
name = "stanza"
version = "0.0.1"
description = "A batteries-included ML toolkit"
authors = ["Daniel Pfrommer <dan.pfrommer@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jax = "^0.4.2"
jaxlib = "^0.4.2"
optax = "^0.1.4"
termcolor = "^2.2.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
