[tool.poetry]
name = "stanza"
version = "0.0.1"
description = "A batteries-included ML toolkit"
authors = ["Daniel Pfrommer <dan.pfrommer@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "stanza"}]


[tool.poetry.scripts]
activity = "stanza.runtime:launch_activity"

[tool.poetry.dependencies]
jax = {version = "0.4.10"}
jaxlib = {version = "0.4.10"}
python = ">=3.10,<3.11"
optax = "^0.1.4"
rich = "^13.3.1"
cloudpickle = "^2.2.1"
docker = "^6.0.1"
dockerpty = "^0.4.1"
rpyc = "^5.3.0"
dm-haiku = {git = "https://github.com/deepmind/dm-haiku"}
trajax = { git = "https://github.com/google/trajax" }
wandb = "^0.13.11"
ffmpegio = "^0.8.3"
gdown = "^4.7.1"
zarr = "^2.14.2"
plotly = "^5.14.1"
pandas = "^2.0.1"
pycairo = "^1.23.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "private"
url = "https://packages.pfrommer.dev/packages/staging"
default = false
secondary = false
