[tool.poetry]
name = "stanza"
version = "0.0.1"
description = "A batteries-included ML toolkit"
authors = ["Daniel Pfrommer <dan.pfrommer@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
jax = { extras = ["cuda"], version = "^0.4.1" }
jaxlib = { extras = ["cuda11.cudnn86"], version = "^0.4.1" }
optax = "^0.1.4"
rich = "^13.3.1"
cloudpickle = "^2.2.1"
docker = "^6.0.1"
dockerpty = "^0.4.1"
rpyc = "^5.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[tool.poetry.scripts]
worker_manager = "stanza.experiment.launch_manager:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "private"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
