[project]
name = "stanza"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Daniel Pfrommer", email = "dan.pfrommer@gmail.com"},
]
dependencies = [
    "jax>=0.4.24",
    "rich>=13.7.0",
    "flax>=0.8.1",
    "optax>=0.1.9",
    "pandas>=2.2.0",
    "chex>=0.1.85",
    "numpy>=1.26.4",
    "ffmpegio>=0.9.0",
    "einops>=0.7.0",
    "wandb>=0.16.3",
    "matplotlib>=3.8.2",
    "plotly>=5.18.0",
    "orbax-checkpoint>=0.5.3",
]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
launch = "stanza:launch"

[tool.pdm]
distribution = false
