[tool.poetry]
name = "stanza"
version = "0.1.0"
description = ""
authors = ["Daniel Pfrommer <dan.pfrommer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jax = "^0.4.23"
optax = "^0.1.7"
ffmpegio = "^0.9.0"
matplotlib = "^3.8.2"
plotly = "^5.18.0"
numpy = "^1.26.2"
pandas = "^2.1.4"

[tool.poetry.scripts]
activity = 'stanza.runtime:launch_activity'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# The primary is the local packages,
# then check pypi
[[tool.poetry.source]]
name = "custom"
url = "http://localhost:8666/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "PyPI"
priority = "supplemental"

