[project]
name = "stanza-meta"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Daniel Pfrommer", email = "dan.pfrommer@gmail.com"},
]
dependencies = [
    "stanza[ipython,docs] @ file:///${PROJECT_ROOT}/packages/stanza",
    "stanza-models @ file:///${PROJECT_ROOT}/projects/models",
    "cond_diffusion @ file:///${PROJECT_ROOT}/projects/cond-diffusion",
    "image-classifier @ file:///${PROJECT_ROOT}/projects/image-classifier",
    "language-model @ file:///${PROJECT_ROOT}/projects/language-model",
    "wandb>=0.17.4",
]
requires-python = "<3.11,>=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
cuda12 = [
    "jax[cuda12]>=0.4.30",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "-e stanza[ipython,docs] @ file:///${PROJECT_ROOT}/packages/stanza",
    "-e stanza-model @ file:///${PROJECT_ROOT}/projects/models",
    "-e cond_diffusion @ file:///${PROJECT_ROOT}/projects/cond-diffusion",
    "-e image-classifier @ file:///${PROJECT_ROOT}/projects/image-classifier",
    "-e language-model @ file:///${PROJECT_ROOT}/projects/language-model",
    "pytest>=8.2.2",
]

# These are annoying and not used...
[tool.pdm.resolution]
excludes = ["pytinyrenderer", "evdev"]

[tool.nixpy]
extra-links = [
	"file://${PROJECT_ROOT}/nix-custom/"
]
