[tool.poetry]
name = "stanza"
version = "0.0.1"
description = "A batteries-included ML toolkit"
authors = ["Daniel Pfrommer <dan.pfrommer@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "stanza"},
    {include = "diffusion_policy", from = "projects"},
    {include = "latent_diffusion", from = "projects"},
    {include = "sam", from = "projects"},
    {include = "demo", from = "projects"}
]


[tool.poetry.scripts]
activity = "stanza.runtime:launch_activity"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
jax = [
	{version="^0.4.18", optional=true},
	{version="^0.4.18", extras=["cuda12_pip"], optional=true}
]
optax = "^0.1.4"
rich = "^13.3.1"
wandb = "^0.13.11"
ffmpegio = "^0.8.3"
zarr = "^2.14.2"
plotly = "^5.14.1"
kaleido = "0.2.0"
seaborn = "^0.12.2"
dm-haiku = {git = "https://github.com/deepmind/dm-haiku"}
shapely = "1.8.4"
pymunk = "^6.4.0"
drake = "^1.17.0"
typing-extensions = "^4.6.3"
flax = "^0.7.1"
glfw = "^2.6.2"
brax = "^0.9.1"
pot = "^0.9.1"
moviepy = "^1.0.3"
imageio = "^2.31.5"
docker = "^6.1.3"
dockerpty = "^0.4.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
jupyter = "^1.0.0"

[tool.poetry.extras]
cuda = ["jax"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "jax"
url = "https://storage.googleapis.com/jax-releases/jax_releases.html"

[[tool.poetry.source]]
name = "jax_cuda"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
