[project]
name = "stanza"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Daniel Pfrommer", email = "dan.pfrommer@gmail.com"},
]
dependencies = [
    "jax>=0.4.24",
    "rich>=13.7.0",
    "flax>=0.8.1",
    "optax>=0.1.9",
    "pandas>=2.2.0",
    "chex>=0.1.85",
    "numpy>=1.26.4",
    "ffmpegio>=0.9.0",
    "einops>=0.7.0",
    "wandb>=0.16.3",
    "matplotlib>=3.8.2",
    "plotly>=5.18.0",
    "orbax-checkpoint>=0.5.3",
    "shapely>=2.0.3",
    "pymunk>=6.6.0",
    "nbformat>=5.9.2",
]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
cuda12_local = [
    "jax==0.4.24",
    "jaxlib==0.4.24",
    "jax-cuda12-plugin==0.4.24",
]
cuda12_pip = [
    "jax==0.4.24",
    "jaxlib==0.4.24",
    "jax-cuda12-plugin==0.4.24",
    # nvidia pip cuda dependencies
    "nvidia-cublas-cu12>=12.2.5.6",
    "nvidia-cuda-cupti-cu12>=12.2.142",
    "nvidia-cuda-nvcc-cu12>=12.2.140",
    "nvidia-cuda-runtime-cu12>=12.2.140",
    "nvidia-cudnn-cu12>=8.9",
    "nvidia-cufft-cu12>=11.0.8.103",
    "nvidia-cusolver-cu12>=11.5.2",
    "nvidia-cusparse-cu12>=12.1.2.141",
    "nvidia-nccl-cu12>=2.19.3",
    "nvidia-nvjitlink-cu12>=12.2",
]
docs = [
    "sphinx>=7.2.6",
    "sphinx-design>=0.5.0",
    "sphinx-remove-toctrees>=0.0.3",
    "sphinx-copybutton>=0.5.2",
    "sphinx-book-theme>=1.1.2",
    "sphinx-autodoc-typehints>=2.0.0",
    "furo>=2024.1.29",
]

[project.scripts]
launch = "stanza.runtime:launch"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "ipykernel>=6.29.2",
    "ipywidgets>=8.1.2",
]
