[build-system]
requires = ["setuptools >= 61"]
build-backend = "setuptools.build_meta"

[project]
name = "ninja"
version = "@version@"
description = "Ninja is a small build system with a focus on speed"

[project.scripts]
ninja = "ninja:ninja"