[project]
name = "setuptools-rust"
version = "1.10.1"

dependencies = [
    "setuptools>=62.4",
    "semantic_version>=2.8.2,<3",
]

[build-system]
requires = ["setuptools>=62.4", "setuptools_scm"]
build-backend = "setuptools.build_meta"
