[project]
name = "foundry-core"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Daniel Pfrommer", email = "dan.pfrommer@gmail.com"},
]
dependencies = [
    "jax>=0.4.28",
    "rich>=13.7.0",
    "flax>=0.8.1",
    "optax>=0.1.9",
    "pandas>=2.2.0",
    "chex>=0.1.85",
    "numpy>=1.26.4,<2",
    "ffmpegio>=0.9.0",
    "einops>=0.7.0",
    "matplotlib>=3.8.2",
    "plotly>=5.18.0",
    "nbformat>=5.9.2",
    # For google drive parsing
    "beautifulsoup4>=4.12.3",
    "trajax @ https://github.com/google/trajax/archive/c94a637c5a397b3d4100153f25b4b165507b5b20.tar.gz",
    "zarr>=2.18.1",
    "mujoco-mjx>=3.1.6",
    "shapely>=2.0.4",
    "robosuite>=1.4",
    "sentencepiece>=0.2.0",
    "h5py>=3.11.0",
    "wandb>=0.17"
]
requires-python = "<3.11,>=3.10"
license = {text = "MIT"}

[project.optional-dependencies]
ipython = [
    "ipykernel>=6.29.2",
    "ipywidgets>=8.1.2",
    "jupyterlab>=4.1.2",
    "ipywebrtc>=0.6.0",
    "ipyevents>=2.0.2",
]

[tool.pdm]
distribution = true
includes = ["src/foundry/"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
