[project]
name = "argon-core"
version = "0.1.0"
description = "Argon Core library"
authors = [
    {name = "Daniel Pfrommer", email = "dan.pfrommer@gmail.com"},
]
dependencies = [
    "bs4>=0.0.2",
    "chex>=0.1.88",
    "flax>=0.10.2",
    "jax>=0.5.0",
    "ml-dtypes>=0.5.0",
    "pillow>=11.1.0",
    "requests>=2.32.3",
]
requires-python = ">=3.13"
license = {text = "MIT"}

[tool.hatch.build.targets.wheel]
packages = ["src/argon"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
