[project]
name = "foundry-core"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Daniel Pfrommer", email = "dan.pfrommer@gmail.com"},
]
dependencies = [
    "jax>=0.4.28",
    "flax>=0.8.1",
    "optax>=0.1.9",
    "chex>=0.1.85",
    "rich>=13.7.0",
    "numpy>=1.26.4,<2",
    "einops>=0.7.0",
    # For built-in NLP databases
    "tokenizers>=0.20.3",
    # For serialization...
    "ffmpegio>=0.9.0",
    "boto3>=1.35.11",
    "zarr>=2.18.1",
    # For logging...
    "wandb>=0.18",
    "plotly>=5.18.0",
    # For google drive parsing
    "beautifulsoup4>=4.12.3",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[project.optional-dependencies]
ipython = [
    "ipykernel>=6.29.2",
    "ipywidgets>=8.1.2",
    "jupyterlab>=4.1.2",
    "ipywebrtc>=0.6.0",
    "ipyevents>=2.0.2",
    "nbformat>=5.9.2",
]

[tool.pdm]
distribution = true
includes = ["src/foundry/"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
