[package]
name = "stanza"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "stanza"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rustpython-ast = "0.3.0"
rustpython-parser = "0.3.0"
