[project]
name = "mujoco"
version = "3.2.2"
requires-python = ">=3.8"

dependencies = [
    "absl-py",
    "etils[epath]",
    "glfw",
    "numpy",
    "pyopengl"
]

[build-system]
requires = ["setuptools", "cmake", "pybind11"]
build-backend = "setuptools.build_meta"