[project]
name = "tensorstore"
version = "0.1.64"

dependencies = [
    "numpy>=1.22.0",
    "ml_dtypes>=0.3.1",    
]

[build-system]
requires = [
    "setuptools>=30.3.0",
    "wheel",
    "setuptools_scm>=8.1.0",
    "numpy>=2.0.0",
]