on:
  push:
    branches:
     - main
  workflow_dispatch:
jobs:
  build_doc:
    name: Build and Publish Documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.10'
          cache: true
      - name: Install dependencies
        run: pdm install -d -G docs
      - name: Build Documentation
        working-directory: ./docs
        run: make html
      - name: Fix permissions
        run: |
            chmod -c -R +rX "docs/_build/html" | while read line; do
              echo "::warning title=Invalid file permissions automatically fixed::$line"
            done
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html
    
