on:
  push:
    branches:
     - main
  workflow_dispatch:
jobs:
  build_doc:
    name: Build and Publish Documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r docs/requirements.txt
      - run: sphinx-build -b html docs docs/build/html -j auto

    
